"""Keep the "Apple style App" design system in step with the app's real styles.

    python design-system-apple/build.py          # sync, then list what changed
    python design-system-apple/build.py --check  # only report; exit 1 if out of date

The app is the source of truth (hyperocr/static). This script:

- copies colour values, `shadow-lift` and the font stacks from style.css into
  project/tokens.json, keeping every usage note; a colour variable without a
  token (or a token without a variable) stops the build, so new colours get a note;
- writes project/components/bundle.css (style.css without its token blocks) and
  project/components/bundle.js (motion.js, published as window.AppleStyle);
- writes each icon of index.html's sprite to project/assets/Icons/<name>.svg and
  the app icon to project/assets/Logos/app-icon.svg;
- refreshes the icon sprite and the app icon inside every component preview.

Spacing, radius, size and shadow values other than `shadow-lift` live in component
rules, not variables: when a rule changes, update its token in tokens.json by hand.
Publishing the changed files to Claude Design is a separate step (see CLAUDE.md).
"""

from __future__ import annotations

import base64
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE / "project"
STATIC = HERE.parent / "hyperocr" / "static"
BASE_MARK = "/* ------------------------------------------------------------ base */"
FAMILIES = {"font": "text", "font-display": "display", "font-rounded": "rounded", "font-mono": "mono"}
MOTION_VARS = ("ease-spring", "ease-bounce", "spring")
SPRITE = re.compile(r"(<!-- sprite:start -->)(.*?)(<!-- sprite:end -->)", re.S)
APP_ICON = re.compile(r'(<img class="app-icon"[^>]*? src=")[^"]*(")')
INK = "#000000"   # icons as files can't inherit colour: drawn in `label` (light)


def _lf(text: str) -> str:
    """Line endings don't count: a Windows checkout may have turned LF into CRLF."""
    return text.replace("\r\n", "\n")


def css_vars(block: str) -> dict[str, str]:
    return {m.group(1): " ".join(m.group(2).split()) for m in re.finditer(r"--([\w-]+):\s*([^;]+);", block)}


def read_style() -> tuple[str, dict[str, str], dict[str, str]]:
    css = _lf((STATIC / "style.css").read_text(encoding="utf-8"))
    light = re.search(r"^:root \{(.*?)^\}", css, re.S | re.M)
    dark = re.search(r'^:root\[data-theme="dark"\] \{(.*?)^\}', css, re.S | re.M)
    if not light or not dark or BASE_MARK not in css:
        sys.exit("style.css no longer has the expected :root, :root[data-theme=\"dark\"] and base blocks")
    return css, css_vars(light.group(1)), css_vars(dark.group(1))


def is_color(value: str) -> bool:
    return value.startswith("#") or value.startswith(("rgb", "hsl", "oklch"))


def sync_tokens(light: dict[str, str], dark: dict[str, str]) -> str:
    tokens = json.loads(_lf((PROJECT / "tokens.json").read_text(encoding="utf-8")))
    by_name = {t["name"]: t for t in tokens["color"]["tokens"]}
    css_colors = [n for n, v in light.items() if is_color(v)]
    missing = [n for n in css_colors if n not in by_name]
    stale = [n for n in by_name if n not in light]
    if missing or stale:
        msg = []
        if missing:
            msg.append("colours in style.css with no token (add them with a usage note): " + ", ".join(missing))
        if stale:
            msg.append("tokens with no variable in style.css (remove them): " + ", ".join(stale))
        sys.exit("\n".join(msg))
    for name in css_colors:
        value = {"light": light[name]}
        if name in dark and dark[name] != light[name]:
            value["dark"] = dark[name]
        by_name[name]["value"] = value
    for t in tokens["shadow"]["tokens"]:
        if t["name"] == "shadow-lift":
            t["value"] = {"light": light["shadow-lift"], "dark": dark.get("shadow-lift", light["shadow-lift"])}
    for var, key in FAMILIES.items():
        tokens["type"]["families"][key] = light[var]
    return json.dumps(tokens, ensure_ascii=False, indent=1) + "\n"


def bundle_css(css: str, light: dict[str, str]) -> str:
    head = ["/* Generated by design-system-apple/build.py from hyperocr/static/style.css. Edit that file. */",
            ":root {", "  --font: var(--font-text);"]
    head += ["  --%s: %s;" % (v, light[v]) for v in MOTION_VARS]
    head += ["}", ""]
    return "\n".join(head) + css[css.index(BASE_MARK):]


def bundle_js() -> str:
    js = _lf((STATIC / "motion.js").read_text(encoding="utf-8"))
    if "</script" in js.lower() or "<!--" in js:
        sys.exit("motion.js contains </script or <!--, which a bundle may not")
    header = '/* @ds-bundle: {"format":4,"namespace":"AppleStyle","components":[]} */'
    return "%s\n%s\nwindow.AppleStyle = window.HOCR.motion;\n" % (header, js.rstrip())


def sprite_and_icons() -> tuple[str, dict[str, str]]:
    html = _lf((STATIC / "index.html").read_text(encoding="utf-8"))
    m = re.search(r'<svg class="sprite"[^>]*>.*?</svg>', html, re.S)
    if not m:
        sys.exit("index.html has no icon sprite")
    sprite = m.group(0)
    icons = {}
    for sym in re.finditer(r'<symbol id="i-([\w-]+)" viewBox="([^"]+)">(.*?)</symbol>', sprite, re.S):
        name, box, body = sym.groups()
        body = body.replace('fill="currentColor"', 'fill="%s"' % INK)
        icons[name] = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="%s" width="24" height="24" fill="none" '
                       'stroke="%s" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">%s</svg>\n'
                       % (box, INK, body))
    return sprite, icons


def main() -> None:
    check = "--check" in sys.argv
    css, light, dark = read_style()
    sprite, icons = sprite_and_icons()
    out: dict[Path, str] = {
        PROJECT / "tokens.json": sync_tokens(light, dark),
        PROJECT / "components" / "bundle.css": bundle_css(css, light),
        PROJECT / "components" / "bundle.js": bundle_js(),
        PROJECT / "assets" / "Logos" / "app-icon.svg": _lf((STATIC / "icon.svg").read_text(encoding="utf-8")),
    }
    for name, svg in icons.items():
        out[PROJECT / "assets" / "Icons" / ("%s.svg" % name)] = svg
    icon_svg = _lf((STATIC / "icon.svg").read_text(encoding="utf-8")).encode("utf-8")
    icon_uri = "data:image/svg+xml;base64," + base64.b64encode(icon_svg).decode()
    for preview in sorted((PROJECT / "components").glob("*/preview.html")):
        text = _lf(preview.read_text(encoding="utf-8"))
        text = SPRITE.sub(lambda m: m.group(1) + "\n" + sprite + "\n" + m.group(3), text)
        text = APP_ICON.sub(lambda m: m.group(1) + icon_uri + m.group(2), text)
        out[preview] = text
    old_icons = {p for p in (PROJECT / "assets" / "Icons").glob("*.svg")} - set(out)

    changed = [p for p, text in out.items() if not p.exists() or _lf(p.read_text(encoding="utf-8")) != _lf(text)]
    for p in changed:
        print(("out of date: " if check else "wrote: ") + str(p.relative_to(HERE)))
    for p in sorted(old_icons):
        print(("stale icon: " if check else "removed: ") + str(p.relative_to(HERE)))
    if check:
        sys.exit(1 if changed or old_icons else 0)
    for p in changed:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(out[p], encoding="utf-8")
    for p in old_icons:
        p.unlink()
    if not changed and not old_icons:
        print("design system is up to date")
    digest = hashlib.sha256(b"".join(sorted(t.encode() for t in out.values()))).hexdigest()[:12]
    print("content hash", digest)


if __name__ == "__main__":
    main()
